security:
    providers:
        fetcher:
            id: App\Security\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_token:
            pattern: ^/token$
            security: false
        api:
            pattern: ^/
            anonymous: true
            stateless: true
            oauth2: true
    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_USER
    access_control:
        - { path: ^/profile/.*, role: ROLE_USER }
